### PR TITLE
Removed occurences of qc and lab from Verigreen project

### PR DESCRIPTION
**Pull request by borzamircea**

### CODE REVIEW

**Comment by eitansch** [comment]
TEQCommand is irrelevant for removal purposes. It should be restored back (less noise).
Have you tested that we have no regressions?

**Comment by eitansch** [comment]
What about vg-common/src/Spring/command-executer-context.xml? Why did you change TEQ to TE there?

**Comment by rqc** [comment]
What was the resolution on this?

**Comment by borzamircea** [comment]
Will revert and push.

**Pull request merged**
