### PR TITLE
Externalized cacheloader to location pointed by VG_HOME. Works on win…

### PR DESCRIPTION
**Pull request by borzamircea**
…/lin

### CODE REVIEW

**Comment by soninob** [comment]
Did you check it on Linux machine?
Please see the following exception:
Caused by:
java.io.IOException: Unable to create cache loader location /${env.VG_HOME}/cacheloader

Could it be that you already have the cacheloader folder at place?

**Comment by soninob** [comment]
@borzamircea - what is the status on this one? do you have any update?

**Comment by borzamircea** [comment]
Last time I talked to Eitan, we agreed that it works with bash and windows (maybe explicitly state that and promise an update for tcsh)

**Comment by borzamircea** [comment]
Closed by #72 , which is merged with the latest version of VG.

**Pull request closed without merging**
