### PR TITLE
Verigreen service script updates

### PR DESCRIPTION
**Pull request by edagan**
1. Set container restart for run command by setting a script parameter RESTART_OPT
2. Script is not set to use the correct docker image: verigreen/vg-collector

### CODE REVIEW

**Comment by rqc** [comment]
@edagan I am not sure that you want to distribute this script under the verigreen/verigreen repo. The reason is that it is decoupled from the source that it is part of. For instance we could have the situation where the `verigreen/vg-collector:latest` image might end up pointing to `verigreen/vg-collector:2.0.1` but the source code is on tag `3.0.0`. Then you have this disparity. I would distribute this under a different repo such as `verigreen/scripts` and maintain that separately. @eitanshp @soninob @edagan What do you think?

**Comment by edagan** [comment]
I don't really mind. However, this script is not expected to change significantly (or at all) between releases.

**Comment by eitansch** [comment]
@rqc - I tend to agree, just for brevity.
@edagan - please move it to a separate repo (verigreen/scripts or verigreen/utils)

**Comment by soninob** [comment]
Following my discussion with @eitanshp, @elidagan - I suggest you will create a folder utils/script under verigreen repository and put all scripts there.
This folder will not be part of the Docker container.
On the same level - move repository verigreen-reporting to be a folder under verigreen and remove deprecate the repository.

**Comment by rqc** [comment]
@soninob I disagree for the reasons I stated above. Use repos, not folders. I think you actually suggested this approach for the `Dockerfile` for the collector image and it worked great for us since we didn't affect the verigreen development cycle.

**Comment by soninob** [comment]
@rqc - you are right, I did suggest it for the docker file but in this case this is actually a script that should be available for the DevOps team that clone VG repo, including copyHooks.sh and cleanBranches.sh and other tools that we are supplying in VG repo (encrypt password, etc.)
My 2 cents.

**Comment by edagan** [comment]
As we discussed, placing all scripts within a utils folder.

**Pull request merged**
