### PR TITLE
 "public static" fields should be constant

### PR DESCRIPTION
**Pull request by AymanDF**
This pull request is focused on resolving occurrences of Sonar rule squid:S1444 - “"public static" fields should be constant”. You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1444
Please let me know if you have any questions.
Ayman Abdelghany.

### CODE REVIEW

**Comment by soninob** [comment]
@AymanDF - you have  Compilation failure in this PR.

**Comment by AymanDF** [comment]
@soninob Sorry for inconvenience, it has been fixed now.

**Comment by soninob** [comment]
@AymanDF - properties is a dynamic field - we are using Watchdir to identify changes in the properties file, and just might want this object to be changed.
Do you still think that this PR is needed?

**Comment by AymanDF** [comment]
@soninob In this case I don't think this PR is needed :)

**Pull request closed without merging**
