### PR TITLE
Upgrade vg-rest-client to Collections v3.2.2

### PR DESCRIPTION
**Pull request by jart**
Same as #114 but in a different file.

### CODE REVIEW

**Comment by soninob** [comment]
@jart - Thank you for this PR - to approve it you will need to sign the [Contributor License Agreement](https://www.clahub.com/agreements/Verigreen/verigreen)

**Comment by jart** [comment]
I'm sorry I'm not able to sign any CLAs. I encourage you to make this change yourself, now that I've brought the problem to your attention.

**Comment by eitansch** [comment]
Hi @jart - for educational purposes - can you please share your reluctance to sign the CLA? It basically validates your right to contribute the code. I'd appreciate your feedback as I can take it with our legal department and explain the reluctance contributors might feel towards CLAs.
Thanks in advance!

**Comment by jart** [comment]
I would have been happy to sign your CLA. I think it's a perfectly reasonable request. However it would violate the policies of my employer if I were to sign one. That is unless of course your company had already negotiated a corporate CLA with mine.

I think what's important here is that I brought the issue to your attention. This is a trivial change so you should have no problem going forward and making it on your own. That way the lawyers are happy and your users are secure :)

**Pull request closed without merging**
